import pygame,os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))

try:
	SETTINGS = eval(file(os.path.join(BASE_DIR,'settings.txt'), 'r').read().strip().replace('\n',''))
except IOError, e:
	if e.args[0] == 2:
		SETTINGS = {}
	else:
		raise

VERSION = (0,-1,-5)
LONG_VERSION = 'v%s.%s.%s' % VERSION

SIZE = (800,600)
MOVE_SIZE = 50
SCREEN_RECT = pygame.Rect((0,0),SIZE)
FULLSCREEN = True

FONT = pygame.font.Font(None,16)
MID_FONT = pygame.font.Font(None,24)
BIG_FONT = pygame.font.Font(None,32)
FONT_SIZE = FONT.size(''.join([chr(x) for x in range(256)]))
MID_FONT_SIZE = MID_FONT.size(''.join([chr(x) for x in range(256)]))
BIG_FONT_SIZE = BIG_FONT.size(''.join([chr(x) for x in range(256)]))
ANTI_ALIAS = True

CACHE_IMAGES = True

REPEAT_DELAY = 100
REPEAT_INTERVAL = 10

FPS_MAX = 30
CLOCK = pygame.time.Clock()
GRAV_CONST = 3.3475
MASS_MAX = 750
MASS_HABITABLE = 600

EXPLOSION_RANGE = (0.16666666666666666,0)

PARTICLES = 100
PARTICLE_AMOUNTS = {
	'debry':10,
	'star fields':2,
	'stars per field':100,
}
def particles(type):
	return int(PARTICLE_AMOUNTS[type] * (PARTICLES / 100.0))
DEBRY_LIFE = 15.0
STAR_COLORS = [
	(255,255,255),
	(255,255,0),
	(255,200,200),
	(200,255,255),
	(150,150,150)
]

PLAYER_MAX = 8
PLAYER_MAXNAME = 15
PLAYER_MAXPOWER = 1000.0
PLAYER_COLORS = [
	(255,0,0),
	(0,0,255),
	(0,255,0),
	(255,255,0),
	(0,255,255),
	(255,255,255),
	(255,0,255),
	(128,0,255),
	(192,192,192),
	(128,64,0),
]
PLAYER = [(0,-7),(5,-7),(8,-4),(8,4),(5,7),(0,7)]
PLAYER_TURRET_BASE = (8,0)
SHOT_VELOCITY = 15
SHOT_OUTSIDE_LIFE = 250

# TOOLBOX_TITLEHEIGHT = 5+FONT_SIZE[1]
# TOOLBOX_LINESIZE = max(16,FONT_SIZE[1])
# TOOLBOX_SIZE = [200+FONT.size('1000/1000')[0],24+TOOLBOX_TITLEHEIGHT+TOOLBOX_LINESIZE*3]
# TOOLBOX_WEAPONS = (TOOLBOX_SIZE[0]-138,TOOLBOX_TITLEHEIGHT+11)
# TOOLBOX_WEAPONS_WIDTH = 115
# TOOLBOX_DIAL = (32,TOOLBOX_TITLEHEIGHT+31)
# TOOLBOX_POWERBAR = (12,TOOLBOX_TITLEHEIGHT+TOOLBOX_LINESIZE*3+1)
# TOOLBOX_SCROLLHEIGHT = TOOLBOX_LINESIZE*3-22
# ICON_SIZE = (16,16)
ICON_SIZE = (16,16)
TOOLBOX_TITLEHEIGHT = 5+FONT_SIZE[1]
TOOLBOX_RADAR = (8,TOOLBOX_TITLEHEIGHT+6)
TOOLBOX_RADARDIM = (100,100)
TOOLBOX_LINE = (17+TOOLBOX_RADARDIM[0],7+TOOLBOX_TITLEHEIGHT)
TOOLBOX_LINEHEIGHT = max(ICON_SIZE[1],FONT_SIZE[1])
TOOLBOX_LINES = int((TOOLBOX_RADARDIM[1]-2) / TOOLBOX_LINEHEIGHT)
TOOLBOX_LINEWIDTH = FONT.size('W' * 15)[0]
TOOLBOX_AMMOWIDTH = FONT.size('999')[0]
TOOLBOX_LINESDIM = (ICON_SIZE[0]+TOOLBOX_LINEWIDTH+TOOLBOX_AMMOWIDTH,TOOLBOX_LINEHEIGHT*TOOLBOX_LINES)
TOOLBOX_DIALLENGTH = 20
TOOLBOX_DIAL = (8+TOOLBOX_DIALLENGTH,12+TOOLBOX_TITLEHEIGHT+TOOLBOX_RADARDIM[1]+TOOLBOX_DIALLENGTH)
TOOLBOX_DIALTEXT = (5+TOOLBOX_DIAL[0]+TOOLBOX_DIALLENGTH,TOOLBOX_DIAL[1]-TOOLBOX_DIALLENGTH/2-FONT_SIZE[1]/2)
TOOLBOX_DIALWIDTH = FONT.size('90')[0] + 6
TOOLBOX_POWERDIM = (40,10)
TOOLBOX_POWER = (20+TOOLBOX_DIAL[0]+TOOLBOX_DIALLENGTH+TOOLBOX_DIALWIDTH,12+TOOLBOX_TITLEHEIGHT+TOOLBOX_RADARDIM[1]+(TOOLBOX_DIALLENGTH/2)-(TOOLBOX_POWERDIM[1]/2))
TOOLBOX_POWERTEXT = (TOOLBOX_POWER[0]+TOOLBOX_POWERDIM[0]+5,12+TOOLBOX_TITLEHEIGHT+TOOLBOX_RADARDIM[1]+(TOOLBOX_DIALLENGTH/2)-(FONT_SIZE[1]/2))
TOOLBOX_POWERWIDTH = FONT.size('1000/1000')[0]
TOOLBOX_SCROLLBUTTON = (10,10)
TOOLBOX_SCROLLUP = (1+TOOLBOX_LINE[0]+TOOLBOX_LINESDIM[0],TOOLBOX_LINE[1])
TOOLBOX_SCROLLDOWN = (TOOLBOX_SCROLLUP[0],TOOLBOX_SCROLLUP[1]+TOOLBOX_LINEHEIGHT*TOOLBOX_LINES-TOOLBOX_SCROLLBUTTON[1])
TOOLBOX_SCROLLBAR = (TOOLBOX_SCROLLUP[0],TOOLBOX_SCROLLUP[1]+TOOLBOX_SCROLLBUTTON[1]+1)
TOOLBOX_SCROLL = (TOOLBOX_SCROLLUP[0],TOOLBOX_SCROLLUP[1]+TOOLBOX_SCROLLBUTTON[1])
TOOLBOX_SCROLLDIM = (TOOLBOX_SCROLLBUTTON[0],TOOLBOX_SCROLLDOWN[1]-TOOLBOX_SCROLLUP[1]-TOOLBOX_SCROLLBUTTON[1]-2)
TOOLBOX_SIZE = (9+TOOLBOX_SCROLLUP[0]+TOOLBOX_SCROLLBUTTON[0],8+TOOLBOX_DIAL[1])
TOOLBOX_MINIMIZEDIM = (10,10)
TOOLBOX_MINIMIZE = (TOOLBOX_SIZE[0]-8-TOOLBOX_MINIMIZEDIM[0],(TOOLBOX_TITLEHEIGHT+1)/2-TOOLBOX_MINIMIZEDIM[1]/2)

GUI_SEPERATORHEIGHT = BIG_FONT_SIZE[1]